DO
$$
    DECLARE
        scriptName VARCHAR := 'Create auth stub table';
    BEGIN
        RAISE NOTICE 'Start of % ...', scriptName;
        CREATE TABLE IF NOT EXISTS auth_metadata
        (
            id              SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            authorized_user BIGINT NOT NULL
                CONSTRAINT auth_metadata_authorized_user_ref REFERENCES "user"
        );
        COMMENT ON TABLE auth_metadata IS 'Table that acts as an authentication stub';
        COMMENT ON COLUMN auth_metadata.authorized_user IS 'Unique ID of the user that acts as if he is authorized, see "USER" table';
    END
$$