DO
$$
    DECLARE
        scriptName VARCHAR := 'Create auth stub table';
    BEGIN
        RAISE NOTICE 'Start of % ...', scriptName;
        CREATE TABLE IF NOT EXISTS auth_metadata
        (
            id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            person_id BIGINT NOT NULL
                CONSTRAINT auth_metadata_authorized_person_ref REFERENCES person
        );
        COMMENT ON TABLE auth_metadata IS 'Table that acts as an authentication stub';
        COMMENT ON COLUMN auth_metadata.person_id IS 'Unique ID of the person that acts as if he is authorized, see "USER" table';
    END
$$